#ddev-generated
hooks:
  post-start:
    - exec-host: "bash .ddev/scripts/start-redis-insight.bash"
    - exec-host: "bash .ddev/scripts/add-traefik-config.bash"
  pre-stop:
    - exec-host: "bash .ddev/scripts/stop-redis-insight.bash"
