#ddev-generated
services:
  redis-insight:
    container_name: ddev-redis-insight
    image: oblakstudio/redis-insight:master
    user: "${DDEV_UID}:${DDEV_GID}"
    volumes:
      - redis-insight:/home/node:rw
    environment:
      GNOME_KEYRING_PASS: "ddev"
      CONNECTIONS_TIMEOUT_DEFAULT: "10000"
      STDOUT_LOGGER: "true"
      FILES_LOGGER: "false"
    restart: "no"
    expose:
      - "5000"
    networks:
      - ddev_default
    cap_add:
      - IPC_LOCK
volumes:
  redis-insight:
    name: ddev-redis-insight
